export enum Mutations {
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  LOAD_PROJECTS = 'LOAD_PROJECTS',
  UPDATE_PROJECT_ID = 'UPDATE_PROJECT_ID',
  DISPLAY_NOTIFICATION = 'DISPLAY_NOTIFICATION'
}

export enum Actions {
  GET_USER = 'GET_USER',
  GET_USER_PROJECTS = 'GET_USER_PROJECTS',
  OPEN_PROJECT = 'OPEN_PROJECT',
  ADD_TRANSFER = 'ADD_TRANSFER'
}

export enum Collections {
  PROJECTS = 'projects',
  USERS = 'users',
  TRANSFERS = 'transfers'
}
